---
- name: Create librenms user
  ansible.builtin.user:
    name: librenms
    home: /home/librenms
    create_home: true
    system: true
    shell: /bin/bash

- name: Add apache user to librenms group
  ansible.builtin.user:
    name: www-data
    groups: www-data,librenms
